server:
  port: 8090

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/population?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: zy.demo.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug